# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 898)
        MainWindow.setMinimumSize(QtCore.QSize(900, 0))
        MainWindow.setMaximumSize(QtCore.QSize(900, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(0, 90, 378, 16))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(370, -10, 16, 567))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(410, 50, 451, 491))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_7 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_29 = QtWidgets.QLabel(self.frame_7)
        self.label_29.setGeometry(QtCore.QRect(408, 24, 31, 16))
        self.label_29.setObjectName("label_29")
        self.FKLabelArt1 = QtWidgets.QLabel(self.frame_7)
        self.FKLabelArt1.setGeometry(QtCore.QRect(10, 10, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.FKLabelArt1.setFont(font)
        self.FKLabelArt1.setObjectName("FKLabelArt1")
        self.FKSliderArt1 = QtWidgets.QSlider(self.frame_7)
        self.FKSliderArt1.setGeometry(QtCore.QRect(140, 4, 281, 22))
        self.FKSliderArt1.setMinimum(-1800)
        self.FKSliderArt1.setMaximum(1800)
        self.FKSliderArt1.setSingleStep(10)
        self.FKSliderArt1.setPageStep(100)
        self.FKSliderArt1.setTracking(True)
        self.FKSliderArt1.setOrientation(QtCore.Qt.Horizontal)
        self.FKSliderArt1.setInvertedAppearance(False)
        self.FKSliderArt1.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.FKSliderArt1.setTickInterval(200)
        self.FKSliderArt1.setObjectName("FKSliderArt1")
        self.label_31 = QtWidgets.QLabel(self.frame_7)
        self.label_31.setGeometry(QtCore.QRect(278, 24, 16, 16))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.frame_7)
        self.label_32.setGeometry(QtCore.QRect(132, 24, 31, 16))
        self.label_32.setObjectName("label_32")
        self.line_9 = QtWidgets.QFrame(self.frame_7)
        self.line_9.setGeometry(QtCore.QRect(105, 5, 20, 71))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.SpinBoxArt1 = QtWidgets.QDoubleSpinBox(self.frame_7)
        self.SpinBoxArt1.setGeometry(QtCore.QRect(25, 40, 62, 22))
        self.SpinBoxArt1.setAlignment(QtCore.Qt.AlignCenter)
        self.SpinBoxArt1.setDecimals(1)
        self.SpinBoxArt1.setMinimum(-180.0)
        self.SpinBoxArt1.setMaximum(180.0)
        self.SpinBoxArt1.setObjectName("SpinBoxArt1")
        self.FKInc10ButtonArt1 = QtWidgets.QPushButton(self.frame_7)
        self.FKInc10ButtonArt1.setGeometry(QtCore.QRect(385, 50, 41, 23))
        self.FKInc10ButtonArt1.setObjectName("FKInc10ButtonArt1")
        self.FKDec1ButtonArt1 = QtWidgets.QPushButton(self.frame_7)
        self.FKDec1ButtonArt1.setGeometry(QtCore.QRect(185, 50, 41, 23))
        self.FKDec1ButtonArt1.setObjectName("FKDec1ButtonArt1")
        self.FKDec0_1ButtonArt1 = QtWidgets.QPushButton(self.frame_7)
        self.FKDec0_1ButtonArt1.setGeometry(QtCore.QRect(235, 50, 41, 23))
        self.FKDec0_1ButtonArt1.setObjectName("FKDec0_1ButtonArt1")
        self.FKInc0_1ButtonArt1 = QtWidgets.QPushButton(self.frame_7)
        self.FKInc0_1ButtonArt1.setGeometry(QtCore.QRect(285, 50, 41, 23))
        self.FKInc0_1ButtonArt1.setObjectName("FKInc0_1ButtonArt1")
        self.FKInc1ButtonArt1 = QtWidgets.QPushButton(self.frame_7)
        self.FKInc1ButtonArt1.setGeometry(QtCore.QRect(335, 50, 41, 23))
        self.FKInc1ButtonArt1.setObjectName("FKInc1ButtonArt1")
        self.FKDec10ButtonArt1 = QtWidgets.QPushButton(self.frame_7)
        self.FKDec10ButtonArt1.setGeometry(QtCore.QRect(135, 50, 41, 23))
        self.FKDec10ButtonArt1.setObjectName("FKDec10ButtonArt1")
        self.verticalLayout_2.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_33 = QtWidgets.QLabel(self.frame_8)
        self.label_33.setGeometry(QtCore.QRect(410, 24, 30, 16))
        self.label_33.setObjectName("label_33")
        self.FKLabelArt2 = QtWidgets.QLabel(self.frame_8)
        self.FKLabelArt2.setGeometry(QtCore.QRect(10, 10, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.FKLabelArt2.setFont(font)
        self.FKLabelArt2.setObjectName("FKLabelArt2")
        self.FKSliderArt2 = QtWidgets.QSlider(self.frame_8)
        self.FKSliderArt2.setGeometry(QtCore.QRect(140, 4, 281, 22))
        self.FKSliderArt2.setMinimum(-900)
        self.FKSliderArt2.setMaximum(900)
        self.FKSliderArt2.setSingleStep(10)
        self.FKSliderArt2.setPageStep(100)
        self.FKSliderArt2.setTracking(True)
        self.FKSliderArt2.setOrientation(QtCore.Qt.Horizontal)
        self.FKSliderArt2.setInvertedAppearance(False)
        self.FKSliderArt2.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.FKSliderArt2.setTickInterval(200)
        self.FKSliderArt2.setObjectName("FKSliderArt2")
        self.label_35 = QtWidgets.QLabel(self.frame_8)
        self.label_35.setGeometry(QtCore.QRect(278, 24, 16, 16))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.frame_8)
        self.label_36.setGeometry(QtCore.QRect(136, 24, 31, 16))
        self.label_36.setObjectName("label_36")
        self.line_10 = QtWidgets.QFrame(self.frame_8)
        self.line_10.setGeometry(QtCore.QRect(105, 5, 20, 71))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.SpinBoxArt2 = QtWidgets.QDoubleSpinBox(self.frame_8)
        self.SpinBoxArt2.setGeometry(QtCore.QRect(25, 40, 62, 22))
        self.SpinBoxArt2.setAlignment(QtCore.Qt.AlignCenter)
        self.SpinBoxArt2.setDecimals(1)
        self.SpinBoxArt2.setMinimum(-180.0)
        self.SpinBoxArt2.setMaximum(180.0)
        self.SpinBoxArt2.setObjectName("SpinBoxArt2")
        self.FKInc10ButtonArt2 = QtWidgets.QPushButton(self.frame_8)
        self.FKInc10ButtonArt2.setGeometry(QtCore.QRect(385, 50, 41, 23))
        self.FKInc10ButtonArt2.setObjectName("FKInc10ButtonArt2")
        self.FKDec1ButtonArt2 = QtWidgets.QPushButton(self.frame_8)
        self.FKDec1ButtonArt2.setGeometry(QtCore.QRect(185, 50, 41, 23))
        self.FKDec1ButtonArt2.setObjectName("FKDec1ButtonArt2")
        self.FKDec0_1ButtonArt2 = QtWidgets.QPushButton(self.frame_8)
        self.FKDec0_1ButtonArt2.setGeometry(QtCore.QRect(235, 50, 41, 23))
        self.FKDec0_1ButtonArt2.setObjectName("FKDec0_1ButtonArt2")
        self.FKInc0_1ButtonArt2 = QtWidgets.QPushButton(self.frame_8)
        self.FKInc0_1ButtonArt2.setGeometry(QtCore.QRect(285, 50, 41, 23))
        self.FKInc0_1ButtonArt2.setObjectName("FKInc0_1ButtonArt2")
        self.FKInc1ButtonArt2 = QtWidgets.QPushButton(self.frame_8)
        self.FKInc1ButtonArt2.setGeometry(QtCore.QRect(335, 50, 41, 23))
        self.FKInc1ButtonArt2.setObjectName("FKInc1ButtonArt2")
        self.FKDec10ButtonArt2 = QtWidgets.QPushButton(self.frame_8)
        self.FKDec10ButtonArt2.setGeometry(QtCore.QRect(135, 50, 41, 23))
        self.FKDec10ButtonArt2.setObjectName("FKDec10ButtonArt2")
        self.verticalLayout_2.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_37 = QtWidgets.QLabel(self.frame_9)
        self.label_37.setGeometry(QtCore.QRect(410, 24, 30, 16))
        self.label_37.setObjectName("label_37")
        self.FKLabelArt3 = QtWidgets.QLabel(self.frame_9)
        self.FKLabelArt3.setGeometry(QtCore.QRect(10, 10, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.FKLabelArt3.setFont(font)
        self.FKLabelArt3.setObjectName("FKLabelArt3")
        self.FKSliderArt3 = QtWidgets.QSlider(self.frame_9)
        self.FKSliderArt3.setGeometry(QtCore.QRect(140, 4, 281, 22))
        self.FKSliderArt3.setMinimum(-900)
        self.FKSliderArt3.setMaximum(900)
        self.FKSliderArt3.setSingleStep(10)
        self.FKSliderArt3.setPageStep(100)
        self.FKSliderArt3.setTracking(True)
        self.FKSliderArt3.setOrientation(QtCore.Qt.Horizontal)
        self.FKSliderArt3.setInvertedAppearance(False)
        self.FKSliderArt3.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.FKSliderArt3.setTickInterval(200)
        self.FKSliderArt3.setObjectName("FKSliderArt3")
        self.label_39 = QtWidgets.QLabel(self.frame_9)
        self.label_39.setGeometry(QtCore.QRect(278, 24, 16, 16))
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.frame_9)
        self.label_40.setGeometry(QtCore.QRect(136, 24, 30, 16))
        self.label_40.setObjectName("label_40")
        self.line_11 = QtWidgets.QFrame(self.frame_9)
        self.line_11.setGeometry(QtCore.QRect(105, 5, 20, 71))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.SpinBoxArt3 = QtWidgets.QDoubleSpinBox(self.frame_9)
        self.SpinBoxArt3.setGeometry(QtCore.QRect(25, 40, 62, 22))
        self.SpinBoxArt3.setAlignment(QtCore.Qt.AlignCenter)
        self.SpinBoxArt3.setDecimals(1)
        self.SpinBoxArt3.setMinimum(-180.0)
        self.SpinBoxArt3.setMaximum(180.0)
        self.SpinBoxArt3.setObjectName("SpinBoxArt3")
        self.FKInc10ButtonArt3 = QtWidgets.QPushButton(self.frame_9)
        self.FKInc10ButtonArt3.setGeometry(QtCore.QRect(385, 50, 41, 23))
        self.FKInc10ButtonArt3.setObjectName("FKInc10ButtonArt3")
        self.FKDec1ButtonArt3 = QtWidgets.QPushButton(self.frame_9)
        self.FKDec1ButtonArt3.setGeometry(QtCore.QRect(185, 50, 41, 23))
        self.FKDec1ButtonArt3.setObjectName("FKDec1ButtonArt3")
        self.FKDec0_1ButtonArt3 = QtWidgets.QPushButton(self.frame_9)
        self.FKDec0_1ButtonArt3.setGeometry(QtCore.QRect(235, 50, 41, 23))
        self.FKDec0_1ButtonArt3.setObjectName("FKDec0_1ButtonArt3")
        self.FKInc0_1ButtonArt3 = QtWidgets.QPushButton(self.frame_9)
        self.FKInc0_1ButtonArt3.setGeometry(QtCore.QRect(285, 50, 41, 23))
        self.FKInc0_1ButtonArt3.setObjectName("FKInc0_1ButtonArt3")
        self.FKInc1ButtonArt3 = QtWidgets.QPushButton(self.frame_9)
        self.FKInc1ButtonArt3.setGeometry(QtCore.QRect(335, 50, 41, 23))
        self.FKInc1ButtonArt3.setObjectName("FKInc1ButtonArt3")
        self.FKDec10ButtonArt3 = QtWidgets.QPushButton(self.frame_9)
        self.FKDec10ButtonArt3.setGeometry(QtCore.QRect(135, 50, 41, 23))
        self.FKDec10ButtonArt3.setObjectName("FKDec10ButtonArt3")
        self.verticalLayout_2.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_41 = QtWidgets.QLabel(self.frame_10)
        self.label_41.setGeometry(QtCore.QRect(408, 24, 31, 16))
        self.label_41.setObjectName("label_41")
        self.FKLabelArt4 = QtWidgets.QLabel(self.frame_10)
        self.FKLabelArt4.setGeometry(QtCore.QRect(10, 10, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.FKLabelArt4.setFont(font)
        self.FKLabelArt4.setObjectName("FKLabelArt4")
        self.FKSliderArt4 = QtWidgets.QSlider(self.frame_10)
        self.FKSliderArt4.setGeometry(QtCore.QRect(140, 4, 281, 22))
        self.FKSliderArt4.setMinimum(-1800)
        self.FKSliderArt4.setMaximum(1800)
        self.FKSliderArt4.setSingleStep(10)
        self.FKSliderArt4.setPageStep(100)
        self.FKSliderArt4.setTracking(True)
        self.FKSliderArt4.setOrientation(QtCore.Qt.Horizontal)
        self.FKSliderArt4.setInvertedAppearance(False)
        self.FKSliderArt4.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.FKSliderArt4.setTickInterval(200)
        self.FKSliderArt4.setObjectName("FKSliderArt4")
        self.label_43 = QtWidgets.QLabel(self.frame_10)
        self.label_43.setGeometry(QtCore.QRect(278, 24, 16, 16))
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.frame_10)
        self.label_44.setGeometry(QtCore.QRect(132, 24, 31, 16))
        self.label_44.setObjectName("label_44")
        self.line_12 = QtWidgets.QFrame(self.frame_10)
        self.line_12.setGeometry(QtCore.QRect(105, 5, 20, 71))
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.SpinBoxArt4 = QtWidgets.QDoubleSpinBox(self.frame_10)
        self.SpinBoxArt4.setGeometry(QtCore.QRect(25, 40, 62, 22))
        self.SpinBoxArt4.setAlignment(QtCore.Qt.AlignCenter)
        self.SpinBoxArt4.setDecimals(1)
        self.SpinBoxArt4.setMinimum(-180.0)
        self.SpinBoxArt4.setMaximum(180.0)
        self.SpinBoxArt4.setObjectName("SpinBoxArt4")
        self.FKInc10ButtonArt4 = QtWidgets.QPushButton(self.frame_10)
        self.FKInc10ButtonArt4.setGeometry(QtCore.QRect(385, 50, 41, 23))
        self.FKInc10ButtonArt4.setObjectName("FKInc10ButtonArt4")
        self.FKDec1ButtonArt4 = QtWidgets.QPushButton(self.frame_10)
        self.FKDec1ButtonArt4.setGeometry(QtCore.QRect(185, 50, 41, 23))
        self.FKDec1ButtonArt4.setObjectName("FKDec1ButtonArt4")
        self.FKDec0_1ButtonArt4 = QtWidgets.QPushButton(self.frame_10)
        self.FKDec0_1ButtonArt4.setGeometry(QtCore.QRect(235, 50, 41, 23))
        self.FKDec0_1ButtonArt4.setObjectName("FKDec0_1ButtonArt4")
        self.FKInc0_1ButtonArt4 = QtWidgets.QPushButton(self.frame_10)
        self.FKInc0_1ButtonArt4.setGeometry(QtCore.QRect(285, 50, 41, 23))
        self.FKInc0_1ButtonArt4.setObjectName("FKInc0_1ButtonArt4")
        self.FKInc1ButtonArt4 = QtWidgets.QPushButton(self.frame_10)
        self.FKInc1ButtonArt4.setGeometry(QtCore.QRect(335, 50, 41, 23))
        self.FKInc1ButtonArt4.setObjectName("FKInc1ButtonArt4")
        self.FKDec10ButtonArt4 = QtWidgets.QPushButton(self.frame_10)
        self.FKDec10ButtonArt4.setGeometry(QtCore.QRect(135, 50, 41, 23))
        self.FKDec10ButtonArt4.setObjectName("FKDec10ButtonArt4")
        self.verticalLayout_2.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_45 = QtWidgets.QLabel(self.frame_11)
        self.label_45.setGeometry(QtCore.QRect(410, 24, 30, 16))
        self.label_45.setObjectName("label_45")
        self.FKLabelArt5 = QtWidgets.QLabel(self.frame_11)
        self.FKLabelArt5.setGeometry(QtCore.QRect(10, 10, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.FKLabelArt5.setFont(font)
        self.FKLabelArt5.setObjectName("FKLabelArt5")
        self.FKSliderArt5 = QtWidgets.QSlider(self.frame_11)
        self.FKSliderArt5.setGeometry(QtCore.QRect(140, 4, 281, 22))
        self.FKSliderArt5.setMinimum(-900)
        self.FKSliderArt5.setMaximum(900)
        self.FKSliderArt5.setSingleStep(10)
        self.FKSliderArt5.setPageStep(100)
        self.FKSliderArt5.setTracking(True)
        self.FKSliderArt5.setOrientation(QtCore.Qt.Horizontal)
        self.FKSliderArt5.setInvertedAppearance(False)
        self.FKSliderArt5.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.FKSliderArt5.setTickInterval(200)
        self.FKSliderArt5.setObjectName("FKSliderArt5")
        self.label_47 = QtWidgets.QLabel(self.frame_11)
        self.label_47.setGeometry(QtCore.QRect(278, 24, 16, 16))
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.frame_11)
        self.label_48.setGeometry(QtCore.QRect(136, 24, 30, 16))
        self.label_48.setObjectName("label_48")
        self.line_13 = QtWidgets.QFrame(self.frame_11)
        self.line_13.setGeometry(QtCore.QRect(105, 5, 20, 71))
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.SpinBoxArt5 = QtWidgets.QDoubleSpinBox(self.frame_11)
        self.SpinBoxArt5.setGeometry(QtCore.QRect(25, 40, 62, 22))
        self.SpinBoxArt5.setAlignment(QtCore.Qt.AlignCenter)
        self.SpinBoxArt5.setDecimals(1)
        self.SpinBoxArt5.setMinimum(-180.0)
        self.SpinBoxArt5.setMaximum(180.0)
        self.SpinBoxArt5.setObjectName("SpinBoxArt5")
        self.FKInc10ButtonArt5 = QtWidgets.QPushButton(self.frame_11)
        self.FKInc10ButtonArt5.setGeometry(QtCore.QRect(385, 50, 41, 23))
        self.FKInc10ButtonArt5.setObjectName("FKInc10ButtonArt5")
        self.FKDec1ButtonArt5 = QtWidgets.QPushButton(self.frame_11)
        self.FKDec1ButtonArt5.setGeometry(QtCore.QRect(185, 50, 41, 23))
        self.FKDec1ButtonArt5.setObjectName("FKDec1ButtonArt5")
        self.FKDec0_1ButtonArt5 = QtWidgets.QPushButton(self.frame_11)
        self.FKDec0_1ButtonArt5.setGeometry(QtCore.QRect(235, 50, 41, 23))
        self.FKDec0_1ButtonArt5.setObjectName("FKDec0_1ButtonArt5")
        self.FKInc0_1ButtonArt5 = QtWidgets.QPushButton(self.frame_11)
        self.FKInc0_1ButtonArt5.setGeometry(QtCore.QRect(285, 50, 41, 23))
        self.FKInc0_1ButtonArt5.setObjectName("FKInc0_1ButtonArt5")
        self.FKInc1ButtonArt5 = QtWidgets.QPushButton(self.frame_11)
        self.FKInc1ButtonArt5.setGeometry(QtCore.QRect(335, 50, 41, 23))
        self.FKInc1ButtonArt5.setObjectName("FKInc1ButtonArt5")
        self.FKDec10ButtonArt5 = QtWidgets.QPushButton(self.frame_11)
        self.FKDec10ButtonArt5.setGeometry(QtCore.QRect(135, 50, 41, 23))
        self.FKDec10ButtonArt5.setObjectName("FKDec10ButtonArt5")
        self.verticalLayout_2.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label_49 = QtWidgets.QLabel(self.frame_12)
        self.label_49.setGeometry(QtCore.QRect(408, 24, 31, 16))
        self.label_49.setObjectName("label_49")
        self.FKLabelArt6 = QtWidgets.QLabel(self.frame_12)
        self.FKLabelArt6.setGeometry(QtCore.QRect(10, 10, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.FKLabelArt6.setFont(font)
        self.FKLabelArt6.setObjectName("FKLabelArt6")
        self.FKSliderArt6 = QtWidgets.QSlider(self.frame_12)
        self.FKSliderArt6.setGeometry(QtCore.QRect(140, 4, 281, 22))
        self.FKSliderArt6.setMinimum(-1800)
        self.FKSliderArt6.setMaximum(1800)
        self.FKSliderArt6.setSingleStep(10)
        self.FKSliderArt6.setPageStep(100)
        self.FKSliderArt6.setTracking(True)
        self.FKSliderArt6.setOrientation(QtCore.Qt.Horizontal)
        self.FKSliderArt6.setInvertedAppearance(False)
        self.FKSliderArt6.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.FKSliderArt6.setTickInterval(200)
        self.FKSliderArt6.setObjectName("FKSliderArt6")
        self.label_51 = QtWidgets.QLabel(self.frame_12)
        self.label_51.setGeometry(QtCore.QRect(278, 24, 16, 16))
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.frame_12)
        self.label_52.setGeometry(QtCore.QRect(132, 24, 31, 16))
        self.label_52.setObjectName("label_52")
        self.line_14 = QtWidgets.QFrame(self.frame_12)
        self.line_14.setGeometry(QtCore.QRect(105, 5, 20, 71))
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.SpinBoxArt6 = QtWidgets.QDoubleSpinBox(self.frame_12)
        self.SpinBoxArt6.setGeometry(QtCore.QRect(25, 40, 62, 22))
        self.SpinBoxArt6.setAlignment(QtCore.Qt.AlignCenter)
        self.SpinBoxArt6.setDecimals(1)
        self.SpinBoxArt6.setMinimum(-180.0)
        self.SpinBoxArt6.setMaximum(180.0)
        self.SpinBoxArt6.setObjectName("SpinBoxArt6")
        self.FKInc10ButtonArt6 = QtWidgets.QPushButton(self.frame_12)
        self.FKInc10ButtonArt6.setGeometry(QtCore.QRect(385, 50, 41, 23))
        self.FKInc10ButtonArt6.setObjectName("FKInc10ButtonArt6")
        self.FKDec1ButtonArt6 = QtWidgets.QPushButton(self.frame_12)
        self.FKDec1ButtonArt6.setGeometry(QtCore.QRect(185, 50, 41, 23))
        self.FKDec1ButtonArt6.setObjectName("FKDec1ButtonArt6")
        self.FKDec0_1ButtonArt6 = QtWidgets.QPushButton(self.frame_12)
        self.FKDec0_1ButtonArt6.setGeometry(QtCore.QRect(235, 50, 41, 23))
        self.FKDec0_1ButtonArt6.setObjectName("FKDec0_1ButtonArt6")
        self.FKInc0_1ButtonArt6 = QtWidgets.QPushButton(self.frame_12)
        self.FKInc0_1ButtonArt6.setGeometry(QtCore.QRect(285, 50, 41, 23))
        self.FKInc0_1ButtonArt6.setObjectName("FKInc0_1ButtonArt6")
        self.FKInc1ButtonArt6 = QtWidgets.QPushButton(self.frame_12)
        self.FKInc1ButtonArt6.setGeometry(QtCore.QRect(335, 50, 41, 23))
        self.FKInc1ButtonArt6.setObjectName("FKInc1ButtonArt6")
        self.FKDec10ButtonArt6 = QtWidgets.QPushButton(self.frame_12)
        self.FKDec10ButtonArt6.setGeometry(QtCore.QRect(135, 50, 41, 23))
        self.FKDec10ButtonArt6.setObjectName("FKDec10ButtonArt6")
        self.verticalLayout_2.addWidget(self.frame_12)
        self.line_15 = QtWidgets.QFrame(self.centralwidget)
        self.line_15.setGeometry(QtCore.QRect(0, 150, 378, 16))
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.MotorsOffButton = QtWidgets.QPushButton(self.centralwidget)
        self.MotorsOffButton.setGeometry(QtCore.QRect(150, 110, 81, 31))
        self.MotorsOffButton.setObjectName("MotorsOffButton")
        self.HomeButton = QtWidgets.QPushButton(self.centralwidget)
        self.HomeButton.setGeometry(QtCore.QRect(30, 110, 81, 31))
        self.HomeButton.setObjectName("HomeButton")
        self.ZeroPositionButton = QtWidgets.QPushButton(self.centralwidget)
        self.ZeroPositionButton.setGeometry(QtCore.QRect(270, 110, 81, 31))
        self.ZeroPositionButton.setObjectName("ZeroPositionButton")
        self.InverseKinematicsLabel = QtWidgets.QLabel(self.centralwidget)
        self.InverseKinematicsLabel.setGeometry(QtCore.QRect(90, 260, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.InverseKinematicsLabel.setFont(font)
        self.InverseKinematicsLabel.setObjectName("InverseKinematicsLabel")
        self.label_54 = QtWidgets.QLabel(self.centralwidget)
        self.label_54.setGeometry(QtCore.QRect(540, 10, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.IkOutputValueFrame = QtWidgets.QFrame(self.centralwidget)
        self.IkOutputValueFrame.setGeometry(QtCore.QRect(80, 520, 221, 21))
        self.IkOutputValueFrame.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.IkOutputValueFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.IkOutputValueFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.IkOutputValueFrame.setObjectName("IkOutputValueFrame")
        self.IkOutputValueZ = QtWidgets.QLabel(self.IkOutputValueFrame)
        self.IkOutputValueZ.setGeometry(QtCore.QRect(172, 2, 61, 16))
        self.IkOutputValueZ.setStyleSheet("background-color: rgba(255, 255, 255,0)")
        self.IkOutputValueZ.setObjectName("IkOutputValueZ")
        self.IkLabelOutputY = QtWidgets.QLabel(self.IkOutputValueFrame)
        self.IkLabelOutputY.setGeometry(QtCore.QRect(83, 0, 21, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.IkLabelOutputY.setFont(font)
        self.IkLabelOutputY.setStyleSheet("background-color: rgba(255, 255, 255,0)")
        self.IkLabelOutputY.setObjectName("IkLabelOutputY")
        self.IkOutputValueX = QtWidgets.QLabel(self.IkOutputValueFrame)
        self.IkOutputValueX.setGeometry(QtCore.QRect(29, 2, 51, 16))
        self.IkOutputValueX.setStyleSheet("background-color: rgba(255, 255, 255,0)")
        self.IkOutputValueX.setObjectName("IkOutputValueX")
        self.IkLabelOutputZ = QtWidgets.QLabel(self.IkOutputValueFrame)
        self.IkLabelOutputZ.setGeometry(QtCore.QRect(153, 0, 21, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.IkLabelOutputZ.setFont(font)
        self.IkLabelOutputZ.setStyleSheet("background-color: rgba(255, 255, 255,0)")
        self.IkLabelOutputZ.setObjectName("IkLabelOutputZ")
        self.IkLabelOutputX = QtWidgets.QLabel(self.IkOutputValueFrame)
        self.IkLabelOutputX.setGeometry(QtCore.QRect(10, 0, 21, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.IkLabelOutputX.setFont(font)
        self.IkLabelOutputX.setStyleSheet("background-color: rgba(255, 255, 255,0)")
        self.IkLabelOutputX.setObjectName("IkLabelOutputX")
        self.IkOutputValueY = QtWidgets.QLabel(self.IkOutputValueFrame)
        self.IkOutputValueY.setGeometry(QtCore.QRect(102, 2, 51, 16))
        self.IkOutputValueY.setStyleSheet("background-color: rgba(255, 255, 255,0)")
        self.IkOutputValueY.setObjectName("IkOutputValueY")
        self.line_16 = QtWidgets.QFrame(self.centralwidget)
        self.line_16.setGeometry(QtCore.QRect(0, 550, 901, 16))
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.ConsoleInput = QtWidgets.QLineEdit(self.centralwidget)
        self.ConsoleInput.setGeometry(QtCore.QRect(40, 810, 711, 20))
        self.ConsoleInput.setObjectName("ConsoleInput")
        self.ConsoleButtonSend = QtWidgets.QPushButton(self.centralwidget)
        self.ConsoleButtonSend.setGeometry(QtCore.QRect(760, 810, 91, 23))
        self.ConsoleButtonSend.setObjectName("ConsoleButtonSend")
        self.checkBoxHideResp = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxHideResp.setGeometry(QtCore.QRect(720, 840, 131, 17))
        self.checkBoxHideResp.setObjectName("checkBoxHideResp")
        self.ConsoleLabel = QtWidgets.QLabel(self.centralwidget)
        self.ConsoleLabel.setGeometry(QtCore.QRect(400, 565, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ConsoleLabel.setFont(font)
        self.ConsoleLabel.setObjectName("ConsoleLabel")
        self.ConsoleOutput = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.ConsoleOutput.setGeometry(QtCore.QRect(40, 600, 811, 201))
        self.ConsoleOutput.setAcceptDrops(False)
        self.ConsoleOutput.setUndoRedoEnabled(False)
        self.ConsoleOutput.setReadOnly(True)
        self.ConsoleOutput.setObjectName("ConsoleOutput")
        self.line_17 = QtWidgets.QFrame(self.centralwidget)
        self.line_17.setGeometry(QtCore.QRect(0, 240, 378, 16))
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.GripperFrame = QtWidgets.QFrame(self.centralwidget)
        self.GripperFrame.setGeometry(QtCore.QRect(0, 160, 371, 80))
        self.GripperFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.GripperFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.GripperFrame.setObjectName("GripperFrame")
        self.GripperLabel = QtWidgets.QLabel(self.GripperFrame)
        self.GripperLabel.setGeometry(QtCore.QRect(22, 10, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.GripperLabel.setFont(font)
        self.GripperLabel.setObjectName("GripperLabel")
        self.Dec1ButtonGripper = QtWidgets.QPushButton(self.GripperFrame)
        self.Dec1ButtonGripper.setGeometry(QtCore.QRect(160, 50, 41, 23))
        self.Dec1ButtonGripper.setObjectName("Dec1ButtonGripper")
        self.Dec10ButtonGripper = QtWidgets.QPushButton(self.GripperFrame)
        self.Dec10ButtonGripper.setGeometry(QtCore.QRect(110, 50, 41, 23))
        self.Dec10ButtonGripper.setObjectName("Dec10ButtonGripper")
        self.SpinBoxGripper = QtWidgets.QDoubleSpinBox(self.GripperFrame)
        self.SpinBoxGripper.setGeometry(QtCore.QRect(20, 40, 51, 22))
        self.SpinBoxGripper.setAlignment(QtCore.Qt.AlignCenter)
        self.SpinBoxGripper.setDecimals(0)
        self.SpinBoxGripper.setMinimum(0.0)
        self.SpinBoxGripper.setMaximum(100.0)
        self.SpinBoxGripper.setObjectName("SpinBoxGripper")
        self.Gripper0Label = QtWidgets.QLabel(self.GripperFrame)
        self.Gripper0Label.setGeometry(QtCore.QRect(110, 30, 16, 16))
        self.Gripper0Label.setObjectName("Gripper0Label")
        self.Gripper100Label = QtWidgets.QLabel(self.GripperFrame)
        self.Gripper100Label.setGeometry(QtCore.QRect(310, 30, 31, 16))
        self.Gripper100Label.setObjectName("Gripper100Label")
        self.Inc10ButtonGripper = QtWidgets.QPushButton(self.GripperFrame)
        self.Inc10ButtonGripper.setGeometry(QtCore.QRect(280, 50, 41, 23))
        self.Inc10ButtonGripper.setObjectName("Inc10ButtonGripper")
        self.Inc1ButtonGripper = QtWidgets.QPushButton(self.GripperFrame)
        self.Inc1ButtonGripper.setGeometry(QtCore.QRect(230, 50, 41, 23))
        self.Inc1ButtonGripper.setObjectName("Inc1ButtonGripper")
        self.SliderGripper = QtWidgets.QSlider(self.GripperFrame)
        self.SliderGripper.setGeometry(QtCore.QRect(110, 10, 211, 22))
        self.SliderGripper.setMinimum(0)
        self.SliderGripper.setMaximum(100)
        self.SliderGripper.setTracking(True)
        self.SliderGripper.setOrientation(QtCore.Qt.Horizontal)
        self.SliderGripper.setInvertedAppearance(False)
        self.SliderGripper.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.SliderGripper.setTickInterval(20)
        self.SliderGripper.setObjectName("SliderGripper")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(36, 480, 321, 31))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.IKInputSpinBoxX = QtWidgets.QDoubleSpinBox(self.frame_4)
        self.IKInputSpinBoxX.setGeometry(QtCore.QRect(15, 6, 82, 20))
        self.IKInputSpinBoxX.setAlignment(QtCore.Qt.AlignCenter)
        self.IKInputSpinBoxX.setDecimals(2)
        self.IKInputSpinBoxX.setMinimum(-999.0)
        self.IKInputSpinBoxX.setMaximum(999.0)
        self.IKInputSpinBoxX.setObjectName("IKInputSpinBoxX")
        self.IKInputSpinBoxY = QtWidgets.QDoubleSpinBox(self.frame_4)
        self.IKInputSpinBoxY.setGeometry(QtCore.QRect(125, 6, 82, 20))
        self.IKInputSpinBoxY.setAlignment(QtCore.Qt.AlignCenter)
        self.IKInputSpinBoxY.setDecimals(2)
        self.IKInputSpinBoxY.setMinimum(-999.0)
        self.IKInputSpinBoxY.setMaximum(999.0)
        self.IKInputSpinBoxY.setObjectName("IKInputSpinBoxY")
        self.IkLabelInputY = QtWidgets.QLabel(self.frame_4)
        self.IkLabelInputY.setGeometry(QtCore.QRect(110, 5, 14, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.IkLabelInputY.setFont(font)
        self.IkLabelInputY.setStyleSheet("background-color: rgba(255, 255, 255,0)")
        self.IkLabelInputY.setObjectName("IkLabelInputY")
        self.IkLabelInputX = QtWidgets.QLabel(self.frame_4)
        self.IkLabelInputX.setGeometry(QtCore.QRect(0, 5, 14, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.IkLabelInputX.setFont(font)
        self.IkLabelInputX.setStyleSheet("background-color: rgba(255, 255, 255,0)")
        self.IkLabelInputX.setObjectName("IkLabelInputX")
        self.IKInputSpinBoxZ = QtWidgets.QDoubleSpinBox(self.frame_4)
        self.IKInputSpinBoxZ.setGeometry(QtCore.QRect(233, 6, 82, 20))
        self.IKInputSpinBoxZ.setAlignment(QtCore.Qt.AlignCenter)
        self.IKInputSpinBoxZ.setDecimals(2)
        self.IKInputSpinBoxZ.setMinimum(-999.0)
        self.IKInputSpinBoxZ.setMaximum(999.0)
        self.IKInputSpinBoxZ.setObjectName("IKInputSpinBoxZ")
        self.IkLabelInputZ = QtWidgets.QLabel(self.frame_4)
        self.IkLabelInputZ.setGeometry(QtCore.QRect(219, 5, 13, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.IkLabelInputZ.setFont(font)
        self.IkLabelInputZ.setStyleSheet("background-color: rgba(255, 255, 255,0)")
        self.IkLabelInputZ.setObjectName("IkLabelInputZ")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setEnabled(False)
        self.frame_5.setGeometry(QtCore.QRect(10, 290, 357, 259))
        self.frame_5.setStyleSheet("background-color:rgba(200, 200, 200, 150)")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 300, 351, 168))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.IkIncButtonZ = QtWidgets.QPushButton(self.layoutWidget1)
        self.IkIncButtonZ.setMinimumSize(QtCore.QSize(50, 50))
        self.IkIncButtonZ.setMaximumSize(QtCore.QSize(50, 50))
        self.IkIncButtonZ.setObjectName("IkIncButtonZ")
        self.verticalLayout.addWidget(self.IkIncButtonZ)
        self.IkDecButtonZ = QtWidgets.QPushButton(self.layoutWidget1)
        self.IkDecButtonZ.setMinimumSize(QtCore.QSize(50, 50))
        self.IkDecButtonZ.setMaximumSize(QtCore.QSize(50, 50))
        self.IkDecButtonZ.setObjectName("IkDecButtonZ")
        self.verticalLayout.addWidget(self.IkDecButtonZ)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(15, 98, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.IkIncButtonY = QtWidgets.QPushButton(self.layoutWidget1)
        self.IkIncButtonY.setMinimumSize(QtCore.QSize(50, 50))
        self.IkIncButtonY.setMaximumSize(QtCore.QSize(50, 50))
        self.IkIncButtonY.setObjectName("IkIncButtonY")
        self.gridLayout.addWidget(self.IkIncButtonY, 1, 2, 1, 1)
        self.IkDecButtonY = QtWidgets.QPushButton(self.layoutWidget1)
        self.IkDecButtonY.setMinimumSize(QtCore.QSize(50, 50))
        self.IkDecButtonY.setMaximumSize(QtCore.QSize(50, 50))
        self.IkDecButtonY.setObjectName("IkDecButtonY")
        self.gridLayout.addWidget(self.IkDecButtonY, 1, 0, 1, 1)
        self.IkIncButtonX = QtWidgets.QPushButton(self.layoutWidget1)
        self.IkIncButtonX.setMinimumSize(QtCore.QSize(50, 50))
        self.IkIncButtonX.setMaximumSize(QtCore.QSize(50, 50))
        self.IkIncButtonX.setObjectName("IkIncButtonX")
        self.gridLayout.addWidget(self.IkIncButtonX, 0, 1, 1, 1)
        self.IkDecButtonX = QtWidgets.QPushButton(self.layoutWidget1)
        self.IkDecButtonX.setMinimumSize(QtCore.QSize(50, 50))
        self.IkDecButtonX.setMaximumSize(QtCore.QSize(50, 50))
        self.IkDecButtonX.setObjectName("IkDecButtonX")
        self.gridLayout.addWidget(self.IkDecButtonX, 2, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_7.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 98, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.frame_3 = QtWidgets.QFrame(self.layoutWidget1)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.IkMultiplierDecSpinBox = QtWidgets.QPushButton(self.frame_3)
        self.IkMultiplierDecSpinBox.setGeometry(QtCore.QRect(43, 110, 31, 23))
        self.IkMultiplierDecSpinBox.setObjectName("IkMultiplierDecSpinBox")
        self.IkMultiplierDiv10SpinBox = QtWidgets.QPushButton(self.frame_3)
        self.IkMultiplierDiv10SpinBox.setGeometry(QtCore.QRect(3, 110, 41, 23))
        self.IkMultiplierDiv10SpinBox.setObjectName("IkMultiplierDiv10SpinBox")
        self.IkMultiplierIncSpinBox = QtWidgets.QPushButton(self.frame_3)
        self.IkMultiplierIncSpinBox.setGeometry(QtCore.QRect(43, 40, 31, 23))
        self.IkMultiplierIncSpinBox.setObjectName("IkMultiplierIncSpinBox")
        self.IkMultiplierX10SpinBox = QtWidgets.QPushButton(self.frame_3)
        self.IkMultiplierX10SpinBox.setGeometry(QtCore.QRect(3, 40, 41, 23))
        self.IkMultiplierX10SpinBox.setObjectName("IkMultiplierX10SpinBox")
        self.IkMultiplierSpinBox = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.IkMultiplierSpinBox.setGeometry(QtCore.QRect(3, 75, 71, 22))
        self.IkMultiplierSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.IkMultiplierSpinBox.setSuffix("")
        self.IkMultiplierSpinBox.setDecimals(1)
        self.IkMultiplierSpinBox.setMinimum(0.0)
        self.IkMultiplierSpinBox.setMaximum(100.0)
        self.IkMultiplierSpinBox.setObjectName("IkMultiplierSpinBox")
        self.horizontalLayout_7.addWidget(self.frame_3)
        self.SerialPortLabel = QtWidgets.QLabel(self.centralwidget)
        self.SerialPortLabel.setGeometry(QtCore.QRect(20, 22, 65, 22))
        self.SerialPortLabel.setMinimumSize(QtCore.QSize(65, 22))
        self.SerialPortLabel.setMaximumSize(QtCore.QSize(65, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.SerialPortLabel.setFont(font)
        self.SerialPortLabel.setObjectName("SerialPortLabel")
        self.RobotStateLabel = QtWidgets.QLabel(self.centralwidget)
        self.RobotStateLabel.setGeometry(QtCore.QRect(216, 22, 38, 22))
        self.RobotStateLabel.setMinimumSize(QtCore.QSize(38, 22))
        self.RobotStateLabel.setMaximumSize(QtCore.QSize(38, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.RobotStateLabel.setFont(font)
        self.RobotStateLabel.setObjectName("RobotStateLabel")
        self.SerialPortComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.SerialPortComboBox.setGeometry(QtCore.QRect(91, 22, 80, 22))
        self.SerialPortComboBox.setMinimumSize(QtCore.QSize(80, 22))
        self.SerialPortComboBox.setMaximumSize(QtCore.QSize(80, 22))
        self.SerialPortComboBox.setObjectName("SerialPortComboBox")
        self.ConnectButton = QtWidgets.QPushButton(self.centralwidget)
        self.ConnectButton.setGeometry(QtCore.QRect(260, 50, 90, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ConnectButton.sizePolicy().hasHeightForWidth())
        self.ConnectButton.setSizePolicy(sizePolicy)
        self.ConnectButton.setMinimumSize(QtCore.QSize(75, 22))
        self.ConnectButton.setMaximumSize(QtCore.QSize(90, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ConnectButton.setFont(font)
        self.ConnectButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ConnectButton.setObjectName("ConnectButton")
        self.SerialPortRefreshButton = QtWidgets.QPushButton(self.centralwidget)
        self.SerialPortRefreshButton.setGeometry(QtCore.QRect(177, 22, 22, 22))
        self.SerialPortRefreshButton.setMinimumSize(QtCore.QSize(22, 22))
        self.SerialPortRefreshButton.setMaximumSize(QtCore.QSize(22, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.SerialPortRefreshButton.setFont(font)
        self.SerialPortRefreshButton.setObjectName("SerialPortRefreshButton")
        self.RobotStateDisplay = QtWidgets.QLabel(self.centralwidget)
        self.RobotStateDisplay.setGeometry(QtCore.QRect(260, 22, 90, 22))
        self.RobotStateDisplay.setMinimumSize(QtCore.QSize(90, 22))
        self.RobotStateDisplay.setMaximumSize(QtCore.QSize(90, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.RobotStateDisplay.setFont(font)
        self.RobotStateDisplay.setStyleSheet("background-color: rgb(255, 0, 4)")
        self.RobotStateDisplay.setFrameShape(QtWidgets.QFrame.Box)
        self.RobotStateDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.RobotStateDisplay.setObjectName("RobotStateDisplay")
        self.BaudRateComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.BaudRateComboBox.setGeometry(QtCore.QRect(91, 50, 80, 22))
        self.BaudRateComboBox.setMinimumSize(QtCore.QSize(80, 22))
        self.BaudRateComboBox.setMaximumSize(QtCore.QSize(80, 22))
        self.BaudRateComboBox.setObjectName("BaudRateComboBox")
        self.BaudRateComboBox.addItem("")
        self.BaudRateComboBox.addItem("")
        self.BaudRateComboBox.addItem("")
        self.BaudRateComboBox.addItem("")
        self.BaudRateComboBox.addItem("")
        self.BaudRateComboBox.addItem("")
        self.BaudRateComboBox.addItem("")
        self.BaudRateComboBox.addItem("")
        self.BaudRateComboBox.addItem("")
        self.BaudRateComboBox.addItem("")
        self.BaudRateComboBox.addItem("")
        self.BaudRateComboBox.addItem("")
        self.BaudRateLabel = QtWidgets.QLabel(self.centralwidget)
        self.BaudRateLabel.setGeometry(QtCore.QRect(20, 50, 65, 22))
        self.BaudRateLabel.setMinimumSize(QtCore.QSize(65, 22))
        self.BaudRateLabel.setMaximumSize(QtCore.QSize(65, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.BaudRateLabel.setFont(font)
        self.BaudRateLabel.setObjectName("BaudRateLabel")
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.line_7.raise_()
        self.line_8.raise_()
        self.line_15.raise_()
        self.MotorsOffButton.raise_()
        self.HomeButton.raise_()
        self.ZeroPositionButton.raise_()
        self.InverseKinematicsLabel.raise_()
        self.label_54.raise_()
        self.IkOutputValueFrame.raise_()
        self.line_16.raise_()
        self.ConsoleInput.raise_()
        self.ConsoleButtonSend.raise_()
        self.checkBoxHideResp.raise_()
        self.ConsoleLabel.raise_()
        self.ConsoleOutput.raise_()
        self.line_17.raise_()
        self.GripperFrame.raise_()
        self.frame_4.raise_()
        self.frame_5.raise_()
        self.SerialPortLabel.raise_()
        self.RobotStateLabel.raise_()
        self.SerialPortComboBox.raise_()
        self.ConnectButton.raise_()
        self.SerialPortRefreshButton.raise_()
        self.RobotStateDisplay.raise_()
        self.BaudRateComboBox.raise_()
        self.BaudRateLabel.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAbout_2 = QtWidgets.QAction(MainWindow)
        self.actionAbout_2.setObjectName("actionAbout_2")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionExit_2 = QtWidgets.QAction(MainWindow)
        self.actionExit_2.setObjectName("actionExit_2")
        self.menuMenu.addAction(self.actionExit)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionExit_2)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout_2)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Asgard"))
        self.label_29.setText(_translate("MainWindow", "180º"))
        self.FKLabelArt1.setText(_translate("MainWindow", "Articulation 1"))
        self.label_31.setText(_translate("MainWindow", "0º"))
        self.label_32.setText(_translate("MainWindow", "-180º"))
        self.SpinBoxArt1.setSuffix(_translate("MainWindow", "º"))
        self.FKInc10ButtonArt1.setText(_translate("MainWindow", "+10º"))
        self.FKDec1ButtonArt1.setText(_translate("MainWindow", "-1º"))
        self.FKDec0_1ButtonArt1.setText(_translate("MainWindow", "-0,1º"))
        self.FKInc0_1ButtonArt1.setText(_translate("MainWindow", "+0,1º"))
        self.FKInc1ButtonArt1.setText(_translate("MainWindow", "+1º"))
        self.FKDec10ButtonArt1.setText(_translate("MainWindow", "-10º"))
        self.label_33.setText(_translate("MainWindow", "90º"))
        self.FKLabelArt2.setText(_translate("MainWindow", "Articulation 2"))
        self.label_35.setText(_translate("MainWindow", "0º"))
        self.label_36.setText(_translate("MainWindow", "-90º"))
        self.SpinBoxArt2.setSuffix(_translate("MainWindow", "º"))
        self.FKInc10ButtonArt2.setText(_translate("MainWindow", "+10º"))
        self.FKDec1ButtonArt2.setText(_translate("MainWindow", "-1º"))
        self.FKDec0_1ButtonArt2.setText(_translate("MainWindow", "-0,1º"))
        self.FKInc0_1ButtonArt2.setText(_translate("MainWindow", "+0,1º"))
        self.FKInc1ButtonArt2.setText(_translate("MainWindow", "+1º"))
        self.FKDec10ButtonArt2.setText(_translate("MainWindow", "-10º"))
        self.label_37.setText(_translate("MainWindow", "90º"))
        self.FKLabelArt3.setText(_translate("MainWindow", "Articulation 3"))
        self.label_39.setText(_translate("MainWindow", "0º"))
        self.label_40.setText(_translate("MainWindow", "-90º"))
        self.SpinBoxArt3.setSuffix(_translate("MainWindow", "º"))
        self.FKInc10ButtonArt3.setText(_translate("MainWindow", "+10º"))
        self.FKDec1ButtonArt3.setText(_translate("MainWindow", "-1º"))
        self.FKDec0_1ButtonArt3.setText(_translate("MainWindow", "-0,1º"))
        self.FKInc0_1ButtonArt3.setText(_translate("MainWindow", "+0,1º"))
        self.FKInc1ButtonArt3.setText(_translate("MainWindow", "+1º"))
        self.FKDec10ButtonArt3.setText(_translate("MainWindow", "-10º"))
        self.label_41.setText(_translate("MainWindow", "180º"))
        self.FKLabelArt4.setText(_translate("MainWindow", "Articulation 4"))
        self.label_43.setText(_translate("MainWindow", "0º"))
        self.label_44.setText(_translate("MainWindow", "-180º"))
        self.SpinBoxArt4.setSuffix(_translate("MainWindow", "º"))
        self.FKInc10ButtonArt4.setText(_translate("MainWindow", "+10º"))
        self.FKDec1ButtonArt4.setText(_translate("MainWindow", "-1º"))
        self.FKDec0_1ButtonArt4.setText(_translate("MainWindow", "-0,1º"))
        self.FKInc0_1ButtonArt4.setText(_translate("MainWindow", "+0,1º"))
        self.FKInc1ButtonArt4.setText(_translate("MainWindow", "+1º"))
        self.FKDec10ButtonArt4.setText(_translate("MainWindow", "-10º"))
        self.label_45.setText(_translate("MainWindow", "90º"))
        self.FKLabelArt5.setText(_translate("MainWindow", "Articulation 5"))
        self.label_47.setText(_translate("MainWindow", "0º"))
        self.label_48.setText(_translate("MainWindow", "-90º"))
        self.SpinBoxArt5.setSuffix(_translate("MainWindow", "º"))
        self.FKInc10ButtonArt5.setText(_translate("MainWindow", "+10º"))
        self.FKDec1ButtonArt5.setText(_translate("MainWindow", "-1º"))
        self.FKDec0_1ButtonArt5.setText(_translate("MainWindow", "-0,1º"))
        self.FKInc0_1ButtonArt5.setText(_translate("MainWindow", "+0,1º"))
        self.FKInc1ButtonArt5.setText(_translate("MainWindow", "+1º"))
        self.FKDec10ButtonArt5.setText(_translate("MainWindow", "-10º"))
        self.label_49.setText(_translate("MainWindow", "180º"))
        self.FKLabelArt6.setText(_translate("MainWindow", "Articulation 6"))
        self.label_51.setText(_translate("MainWindow", "0º"))
        self.label_52.setText(_translate("MainWindow", "-180º"))
        self.SpinBoxArt6.setSuffix(_translate("MainWindow", "º"))
        self.FKInc10ButtonArt6.setText(_translate("MainWindow", "+10º"))
        self.FKDec1ButtonArt6.setText(_translate("MainWindow", "-1º"))
        self.FKDec0_1ButtonArt6.setText(_translate("MainWindow", "-0,1º"))
        self.FKInc0_1ButtonArt6.setText(_translate("MainWindow", "+0,1º"))
        self.FKInc1ButtonArt6.setText(_translate("MainWindow", "+1º"))
        self.FKDec10ButtonArt6.setText(_translate("MainWindow", "-10º"))
        self.MotorsOffButton.setText(_translate("MainWindow", "Motors off"))
        self.HomeButton.setText(_translate("MainWindow", "Home"))
        self.ZeroPositionButton.setText(_translate("MainWindow", "Zero position"))
        self.InverseKinematicsLabel.setText(_translate("MainWindow", "Inverse Kinematics"))
        self.label_54.setText(_translate("MainWindow", "Forward Kinematics"))
        self.IkOutputValueZ.setText(_translate("MainWindow", "200 mm"))
        self.IkLabelOutputY.setText(_translate("MainWindow", "Y:"))
        self.IkOutputValueX.setText(_translate("MainWindow", "200 mm"))
        self.IkLabelOutputZ.setText(_translate("MainWindow", "Z:"))
        self.IkLabelOutputX.setText(_translate("MainWindow", "X:"))
        self.IkOutputValueY.setText(_translate("MainWindow", "200 mm"))
        self.ConsoleButtonSend.setText(_translate("MainWindow", "Send"))
        self.checkBoxHideResp.setText(_translate("MainWindow", "Hide Some Responses"))
        self.ConsoleLabel.setText(_translate("MainWindow", "Console"))
        self.ConsoleOutput.setPlainText(_translate("MainWindow", "G17 G20 G90 G94 G54\n"
"G0 Z0.25\n"
"X-0.5 Y0.2\n"
"Z0.1\n"
"G01 Z0. F5.\n"
"G02 X0. Y0.5 I0.5 J0. F2.5\n"
"X0.5 Y0. I0. J-0.5\n"
"X0. Y-0.5 I-0.5 J0.\n"
"X-0.5 Y0. I0. J0.5\n"
"G01 Z0.1 F5.\n"
"G00 X0. Y0. Z0.25\n"
"G17 G20 G90 G94 G54\n"
"G0 Z0.25\n"
"X-0.5 Y0.2\n"
"Z0.1\n"
"X0.5 Y0. I0. J-0.5\n"
"X0. Y-0.5 I-0.5 J0.\n"
"X-0.5 Y0. I0. J0.5\n"
"G01 Z0.1 F5.\n"
"G00 X0. Y0. Z0.25"))
        self.GripperLabel.setText(_translate("MainWindow", "Gripper"))
        self.Dec1ButtonGripper.setText(_translate("MainWindow", "-1%"))
        self.Dec10ButtonGripper.setText(_translate("MainWindow", "-10%"))
        self.SpinBoxGripper.setSuffix(_translate("MainWindow", "%"))
        self.Gripper0Label.setText(_translate("MainWindow", "0%"))
        self.Gripper100Label.setText(_translate("MainWindow", "100%"))
        self.Inc10ButtonGripper.setText(_translate("MainWindow", "+10%"))
        self.Inc1ButtonGripper.setText(_translate("MainWindow", "+1%"))
        self.IKInputSpinBoxX.setSuffix(_translate("MainWindow", " mm"))
        self.IKInputSpinBoxY.setSuffix(_translate("MainWindow", " mm"))
        self.IkLabelInputY.setText(_translate("MainWindow", "Y:"))
        self.IkLabelInputX.setText(_translate("MainWindow", "X:"))
        self.IKInputSpinBoxZ.setSuffix(_translate("MainWindow", " mm"))
        self.IkLabelInputZ.setText(_translate("MainWindow", "Z:"))
        self.IkIncButtonZ.setText(_translate("MainWindow", "Z+"))
        self.IkDecButtonZ.setText(_translate("MainWindow", "Z-"))
        self.IkIncButtonY.setText(_translate("MainWindow", "Y+"))
        self.IkDecButtonY.setText(_translate("MainWindow", "Y-"))
        self.IkIncButtonX.setText(_translate("MainWindow", "X+"))
        self.IkDecButtonX.setText(_translate("MainWindow", "X-"))
        self.IkMultiplierDecSpinBox.setText(_translate("MainWindow", "-"))
        self.IkMultiplierDiv10SpinBox.setText(_translate("MainWindow", "÷10"))
        self.IkMultiplierIncSpinBox.setText(_translate("MainWindow", "+"))
        self.IkMultiplierX10SpinBox.setText(_translate("MainWindow", "×10"))
        self.SerialPortLabel.setText(_translate("MainWindow", "Serial Port:"))
        self.RobotStateLabel.setText(_translate("MainWindow", "State:"))
        self.ConnectButton.setText(_translate("MainWindow", "Connect"))
        self.SerialPortRefreshButton.setText(_translate("MainWindow", "↺"))
        self.RobotStateDisplay.setText(_translate("MainWindow", "Disconnected"))
        self.BaudRateComboBox.setCurrentText(_translate("MainWindow", "115200"))
        self.BaudRateComboBox.setItemText(0, _translate("MainWindow", "115200"))
        self.BaudRateComboBox.setItemText(1, _translate("MainWindow", "57600"))
        self.BaudRateComboBox.setItemText(2, _translate("MainWindow", "38400"))
        self.BaudRateComboBox.setItemText(3, _translate("MainWindow", "28800"))
        self.BaudRateComboBox.setItemText(4, _translate("MainWindow", "19200"))
        self.BaudRateComboBox.setItemText(5, _translate("MainWindow", "14400"))
        self.BaudRateComboBox.setItemText(6, _translate("MainWindow", "9600"))
        self.BaudRateComboBox.setItemText(7, _translate("MainWindow", "4800"))
        self.BaudRateComboBox.setItemText(8, _translate("MainWindow", "2400"))
        self.BaudRateComboBox.setItemText(9, _translate("MainWindow", "1200"))
        self.BaudRateComboBox.setItemText(10, _translate("MainWindow", "600"))
        self.BaudRateComboBox.setItemText(11, _translate("MainWindow", "300"))
        self.BaudRateLabel.setText(_translate("MainWindow", "Baud Rate:"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "Manual"))
        self.actionAbout_2.setText(_translate("MainWindow", "About ..."))
        self.actionExit.setText(_translate("MainWindow", "Preferences"))
        self.actionExit_2.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

